### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Python-Honeypot#243]
it seems we got a bug, need to check in them.

**Comment by itsdivyanshjain** [comment]
I have tested out file `docker-compose-host.yml` file with different version of `docker-compose` one is `1.27.4` and other is `1.28.4` and noticed that build fails only with version docker-compose `1.28` not with `1.27`

https://forums.docker.com/t/docker-errors-invalidargument-host-network-mode-is-incompatible-with-port-bindings/103492

Above link mentioned a solution in which it shows that not to use `network_mode: host` and `ports` in docker-compose simultaneously and I tried, it works completely fine. If you found this solution relevant, then I will send PR.

Also, I tested `docker-compose.yml` with different version too, and not having build issue in it.

**Comment by dhirensr** [comment]
Hello @itsdivyanshjain ,
from the link I understood,
"
Your container doesnt have to be on the “host” network in order to talk to the other clients on the network/internet.

But if you prefer to run network_mode: host, you can remove the “ports” part from the docker-compose.
Or if you prefer to use the docker network, remove the “network_mode:” part
"

from this I understood, we have to remove network_mode: host from docker-compose-host.yml

@Ali-Razmjoo : what do you think?

**Comment by itsdivyanshjain** [comment]
Hey @dhirensr, 

I think we prefer network_mode: host. so, i tried removing a port from docker-compose-host.yml and it works as well.

**Comment by ChakshuGupta** [comment]
@dhirensr for docker-compose-host file we need network_mode: host so that the API can access the database running on the host system.

@itsdivyanshjain  I agree with you. You can send a PR for this.

**Comment by itsdivyanshjain** [comment]
@ChakshuGupta Sure.

**Comment by Ali-Razmjoo** [comment]
fixed for now 👍
